apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-test
  labels:
    app: nodejs-test
    test: update
spec:
  replicas: 10
  selector:
    matchLabels:
       app: nodejs-test
  template:
    metadata:
      labels:
        app: nodejs-test
    spec:
      containers:
      - name: nodejs-test
        image: 226026992666.dkr.ecr.us-east-1.amazonaws.com/nodejs-test
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 20m
            memory: 20Mi
      priorityClassName: highestuserdefinedpriority 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 3
                
